PUT http://localhost:8080/users/10
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MzY5MzQwNDEsImlhdCI6MTczNjkyNjg0MSwiaWQiOjExfQ.OagB2EB8CRuzKi0lWZB5Y2Z9OLdBDqdn6vF-L4TjDjs

{
    "name": "admin10",
    "phone": "0",
    "email": "admin10@example.com",
    "password": "admin"
}